---
title: "# forest plots for posteriors"
---

```{r}
source("baseline-datasetup.R")

Sys.setenv("BINPREF" = "C:/HYApp/Rtools3.4/mingw_$(WIN)/bin/")

library(brmstools)
```


### Regression analysis

```{r}

df %>% select(PA_agrbct_T1, trackSchool) %>% dplyr::group_by(trackSchool) %>% summarise(mean = mean(PA_agrbct_T1, na.rm = TRUE), n = n())

# Create combination of track and school variables, show means
df %>% dplyr::mutate(trackSchool = paste0(track, school)) %>% select(PA_agrbct_T1, track, school, trackSchool) %>% dplyr::group_by(trackSchool) %>% summarise(mean = mean(PA_agrbct_T1, na.rm = TRUE), n = n())

m_lmer_agrbct <- lme4::lmer(PA_agrbct_T1 ~ (1 | trackSchool), data = df) 
visreg(m_lmer_agrbct, "trackSchool")


```

```{r}

m_agrbct <- brms::bf(PA_agrbct_T1 ~ (1 | track:school)) 
brms::get_prior(m_agrbct, data = df)

fit_agrbct <- brms::brm(m_agrbct, df)

forest(fit_agrbct, sort = TRUE)

plot(fit_agrbct)
pairs(fit_agrbct)
stanplot(fit_agrbct, "b_Intercept", type = "trace")
pp_check(fit_agrbct, nsamples = 100)


fit_agrbct_trackSchoolIntervention <- brms::bf(PA_agrbct_T1 ~ (1 | track:school:intervention)) %>% 
  brms::brm(., data = df, chains = 4, iter = 4000)

fit_agrbct_trackSchoolIntervention %>% summary()
plot(fit_agrbct_trackSchoolIntervention)

ranef(fit_agrbct)
ranef(fit_agrbct_trackSchoolIntervention)

# This gives estimates only:
fit_agrbct_estimates <- ranef(fit_agrbct)[[1]][1:16]

# The 2.5%ile:
fit_agrbct_CIL <- ranef(fit_agrbct)[[1]][33:48]

# The 97.5%ile:
fit_agrbct_CIH <- ranef(fit_agrbct)[[1]][49:64]



PA_agrbct_lmer <- lmer(PA_agrbct_T1 ~ (1 | track:school), data = df)


```



### # forest plots of posteriors

Agreement-related BCTs:

```{r}

m_agrbct <- brms::bf(PA_agrbct_T1 ~ (1 | trackSchool)) 
brms::get_prior(m_agrbct, data = df)

fit_agrbct <- brms::brm(m_agrbct, df, control = list(adapt_delta = 0.95))

# forest(fit_agrbct, sort = TRUE)

plot(fit_agrbct)
pairs(fit_agrbct)
stanplot(fit_agrbct, "b_Intercept", type = "trace")
pp_check(fit_agrbct, nsamples = 100)

```

Accelerometer-measured PA:

```{r}

df <- df %>% mutate(paAccelerometer_T1_centered = paAccelerometer_T1 - mean(paAccelerometer_T1, na.rm = TRUE))

m_paAccelerometer <- brms::bf(paAccelerometer_T1_centered ~ (1 | track:school:intervention)) %>% 
  brms::brm(., data = df, chains = 4, iter = 4000, control = list(adapt_delta = 0.95))

brms::get_prior(m_paAccelerometer_centered, data = df)

# forest(fit_paAccelerometer, sort = TRUE)

plot(fit_paAccelerometer)
pairs(fit_paAccelerometer)
stanplot(fit_paAccelerometer, "b_Intercept", type = "trace")
pp_check(fit_paAccelerometer, nsamples = 100)

```

Plotting the results:

```{r}
color_scheme_set("blue")

df %>% select(paAccelerometer_T1_centered, trackSchool) %>% 
  dplyr::group_by(trackSchool) %>% 
  summarise(mean = mean(paAccelerometer_T1_centered, na.rm = TRUE), n = n())

intercepts <- posterior_samples(m_paAccelerometer, "Intercept")

# Drop the sd and the main intercept, as well as groups with under 10 participants
intercepts <- intercepts %>% select(-`b_Intercept`, 
                                    -`sd_track:school:intervention__Intercept`,
                                    -contains("other"),
                                    -contains("Nursing_2"))

# Clarify names: cut out all before the first "["
names(intercepts) <- str_replace(names(intercepts), ".*\\[", "")
# Change the ending to be more informative by substituting it with group allocation
names(intercepts) <- str_replace(names(intercepts), "_1,Intercept]$", ", intervention")
names(intercepts) <- str_replace(names(intercepts), "_0,Intercept]$", ", control")
names(intercepts) <- str_replace(names(intercepts), "[.]", " ")
names(intercepts) <- str_replace(names(intercepts), "[_]", " ")

m_paAccelerometer_plot <- intercepts %>% mcmc_areas(., prob = .90, prob_outer = .99) +
  labs(x = "Difference from the grand mean") +
  theme_apa(base_size = 12) +
  ggtitle("Moderate-to-vigorous PA: variation in educational tracks")

## Would be nice to draw pies or partially filled rectangles to indicate girl-%.
# m_paAccelerometer_plot +
#   geom_rect(aes(xmin=45, xmax=50, ymin=1, ymax=1.8, fill = "Controlled"), 
#             colour=NA, alpha=0.05) + # Create invisible rectangle for legend
#   geom_rect(aes(xmin=Inf, xmax=Inf, ymin=Inf, ymax=Inf, fill = "Autonomous"), 
#             colour=NA, alpha=0.05) + # Create invisible rectangle for legend
#   scale_fill_manual('Connected node',
#                       values = viridis(2, end = 0.8)[1:2],  
#                       guide = guide_legend(override.aes = list(alpha = 1)))
   
df %>% group_by(trackSchool) %>% select(girl) %>%
  summarise(pct_girl = mean(girl == "1", na.rm = TRUE))

```
