---
title: "Averagerianism"
author: "Matti Heino"
date: "11 huhtikuuta 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Uncorrelated variables

```{r cars}


var1 <- rnorm(n = 700, mean = 100, sd = 20)
var2 <- rnorm(n = 700, mean = 100, sd = 20)
var3 <- rnorm(n = 700, mean = 100, sd = 20)
var4 <- rnorm(n = 700, mean = 100, sd = 20)

corrgram::corrgram(data.frame(var1, var2, var3, var4), lower.panel = panel.pie, upper.panel = panel.conf)
  
middleprobs2 <- function(prob1, prob2) {
sum(var1 >= quantile(var1, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      var1 <= quantile(var1, probs = c(prob1, prob2), na.rm = TRUE)[[2]] &
    var2 >= quantile(var2, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      var2 <= quantile(var2, probs = c(prob1, prob2), na.rm = TRUE)[[2]] &
    var3 >= quantile(var3, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      var3 <= quantile(var3, probs = c(prob1, prob2), na.rm = TRUE)[[2]] &
    var4 >= quantile(var4, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      var4 <= quantile(var4, probs = c(prob1, prob2), na.rm = TRUE)[[2]],
    na.rm= TRUE) 
}    

middle_df3 <- NA

for(i in 1:100) {
middle_df3[i] <- middleprobs2(0.5 - i/2/100, 0.5 + i/2/100) / 700  
}

meansplot_df3 <- data.frame(middle_band_width_perc = c(1:100), hi = 0.5 + middle_df3/2, lo = 0.5 - middle_df3/2)

meansplot_df3 %>% 
  ggplot(aes(y = 100 * hi, x = middle_band_width_perc)) +
  geom_line() +
  geom_line(aes(y = 100 * lo, x = middle_band_width_perc)) +
  labs(title = "The Stereotypical Participant?", 
       y = "% of participants covered above/below median", 
       x = "Definition of average (\"middle x percent\", or \"width of band around the median on all the variables\")") +
  geom_ribbon(aes(ymin = 100 * lo, ymax = 100 * hi), fill="blue", alpha="0.5") +
  scale_y_continuous(breaks = seq(0, 100, by = 10), 
                     labels = c("50", "40", "30", "20", "10", "0", "10", "20", "30", "40", "50")) +
  scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  theme_light()


```

## Correlated variables

```{r}
# Correlated simulated measures

corr_df <- MASS::mvrnorm(700, mu = c(100, 100, 100, 100), Sigma = matrix(c(1.0, 0.99, 0.99, 0.99,
                                                                           0.99, 1.0, 0.99, 0.99,
                                                                           0.99, 0.99, 1.0, 0.99,
                                                                           0.99, 0.99, 0.99, 1.0), 
                                                                         nrow = 4), empirical = TRUE) %>% 
  data.frame()

names(corr_df) <- c("var1", "var2", "var3", "var4")

corrgram::corrgram(corr_df, lower.panel = panel.pie, upper.panel = panel.conf)

middleprobs3 <- function(prob1, prob2) {
sum(corr_df$var1 >= quantile(corr_df$var1, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      corr_df$var1 <= quantile(corr_df$var1, probs = c(prob1, prob2), na.rm = TRUE)[[2]] &
    corr_df$var2 >= quantile(corr_df$var2, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      corr_df$var2 <= quantile(corr_df$var2, probs = c(prob1, prob2), na.rm = TRUE)[[2]] &
    corr_df$var3 >= quantile(corr_df$var3, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      corr_df$var3 <= quantile(corr_df$var3, probs = c(prob1, prob2), na.rm = TRUE)[[2]] &
    corr_df$var4 >= quantile(corr_df$var4, probs = c(prob1, prob2), na.rm = TRUE)[[1]] &
      corr_df$var4 <= quantile(corr_df$var4, probs = c(prob1, prob2), na.rm = TRUE)[[2]],
    na.rm= TRUE) 
}    

middle_df4 <- NA

for(i in 1:100) {
middle_df4[i] <- middleprobs3(0.5 - i/2/100, 0.5 + i/2/100) / 700   
}

meansplot_df4 <- data.frame(middle_band_width_perc = c(1:100), hi = 0.5 + middle_df4/2, lo = 0.5 - middle_df4/2)

meansplot_df4 %>% 
  ggplot(aes(y = 100 * hi, x = middle_band_width_perc)) +
  geom_line() +
  geom_line(aes(y = 100 * lo, x = middle_band_width_perc)) +
  labs(title = "The Stereotypical Participant?", 
       y = "% of participants covered above/below median", 
       x = "Definition of average (\"middle x percent\", or \"width of band around the median on all the variables\")") +
  geom_ribbon(aes(ymin = 100 * lo, ymax = 100 * hi), fill="blue", alpha="0.5") +
  scale_y_continuous(breaks = seq(0, 100, by = 10), 
                     labels = c("50", "40", "30", "20", "10", "0", "10", "20", "30", "40", "50")) +
  scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  theme_light()

```
